var sourcesIndex = JSON.parse('{\
"aho_corasick":["",[["packed",[["teddy",[],["compile.rs","mod.rs","runtime.rs"]]],["api.rs","mod.rs","pattern.rs","rabinkarp.rs","vector.rs"]]],["ahocorasick.rs","automaton.rs","buffer.rs","byte_frequencies.rs","classes.rs","dfa.rs","error.rs","lib.rs","nfa.rs","prefilter.rs","state_id.rs"]],\
"anyhow":["",[],["backtrace.rs","chain.rs","context.rs","ensure.rs","error.rs","fmt.rs","kind.rs","lib.rs","macros.rs","ptr.rs","wrapper.rs"]],\
"atomic_polyfill":["",[],["lib.rs"]],\
"bare_metal":["",[],["lib.rs"]],\
"bitfield":["",[],["lib.rs"]],\
"bitflags":["",[],["lib.rs"]],\
"byteorder":["",[],["lib.rs"]],\
"cfg_if":["",[],["lib.rs"]],\
"clap":["",[["builder",[],["action.rs","app_settings.rs","arg.rs","arg_group.rs","arg_predicate.rs","arg_settings.rs","command.rs","debug_asserts.rs","mod.rs","os_str.rs","possible_value.rs","range.rs","resettable.rs","str.rs","styled_str.rs","value_hint.rs","value_parser.rs"]],["error",[],["context.rs","format.rs","kind.rs","mod.rs"]],["output",[["textwrap",[],["core.rs","mod.rs"]]],["fmt.rs","help.rs","help_template.rs","mod.rs","usage.rs"]],["parser",[["features",[],["mod.rs","suggestions.rs"]],["matches",[],["any_value.rs","arg_matches.rs","matched_arg.rs","mod.rs","value_source.rs"]]],["arg_matcher.rs","error.rs","mod.rs","parser.rs","validator.rs"]],["util",[],["color.rs","flat_map.rs","flat_set.rs","graph.rs","id.rs","mod.rs","str_to_bool.rs"]]],["derive.rs","lib.rs","macros.rs","mkeymap.rs"]],\
"clap_derive":["",[["derives",[],["args.rs","into_app.rs","mod.rs","parser.rs","subcommand.rs","value_enum.rs"]],["utils",[],["doc_comments.rs","mod.rs","spanned.rs","ty.rs"]]],["attr.rs","dummies.rs","item.rs","lib.rs"]],\
"clap_lex":["",[],["lib.rs"]],\
"cortex_m":["",[["peripheral",[],["cbp.rs","cpuid.rs","dcb.rs","dwt.rs","fpb.rs","fpu.rs","icb.rs","itm.rs","mod.rs","mpu.rs","nvic.rs","scb.rs","syst.rs","tpiu.rs"]],["register",[],["basepri.rs","basepri_max.rs","control.rs","faultmask.rs","mod.rs","msp.rs","primask.rs","psp.rs"]]],["asm.rs","call_asm.rs","critical_section.rs","delay.rs","interrupt.rs","itm.rs","lib.rs","macros.rs","prelude.rs"]],\
"critical_section":["",[],["lib.rs","mutex.rs"]],\
"crossbeam_channel":["",[["flavors",[],["array.rs","at.rs","list.rs","mod.rs","never.rs","tick.rs","zero.rs"]]],["channel.rs","context.rs","counter.rs","err.rs","lib.rs","select.rs","select_macro.rs","utils.rs","waker.rs"]],\
"crossbeam_deque":["",[],["deque.rs","lib.rs"]],\
"crossbeam_epoch":["",[["sync",[],["list.rs","mod.rs","once_lock.rs","queue.rs"]]],["atomic.rs","collector.rs","default.rs","deferred.rs","epoch.rs","guard.rs","internal.rs","lib.rs"]],\
"crossbeam_utils":["",[["atomic",[],["atomic_cell.rs","consume.rs","mod.rs","seq_lock.rs"]],["sync",[],["mod.rs","once_lock.rs","parker.rs","sharded_lock.rs","wait_group.rs"]]],["backoff.rs","cache_padded.rs","lib.rs","thread.rs"]],\
"diffy":["",[["diff",[],["cleanup.rs","mod.rs","myers.rs"]],["merge",[],["mod.rs"]],["patch",[],["format.rs","mod.rs","parse.rs"]]],["apply.rs","lib.rs","range.rs","utils.rs"]],\
"either":["",[],["lib.rs"]],\
"embedded_hal":["",[["blocking",[],["can.rs","delay.rs","i2c.rs","mod.rs","rng.rs","serial.rs","spi.rs"]],["can",[],["id.rs","mod.rs","nb.rs"]],["digital",[],["mod.rs","v1.rs","v1_compat.rs","v2.rs","v2_compat.rs"]]],["adc.rs","fmt.rs","lib.rs","prelude.rs","serial.rs","spi.rs","timer.rs","watchdog.rs"]],\
"env_logger":["",[["filter",[],["mod.rs","regex.rs"]],["fmt",[["humantime",[],["extern_impl.rs","mod.rs"]],["writer",[["termcolor",[],["extern_impl.rs","mod.rs"]]],["atty.rs","mod.rs"]]],["mod.rs"]]],["lib.rs"]],\
"exitcode":["",[],["lib.rs"]],\
"fugit":["",[],["aliases.rs","duration.rs","helpers.rs","instant.rs","lib.rs","rate.rs"]],\
"futures_core":["",[["task",[["__internal",[],["atomic_waker.rs","mod.rs"]]],["mod.rs","poll.rs"]]],["future.rs","lib.rs","stream.rs"]],\
"futures_macro":["",[],["executor.rs","join.rs","lib.rs","select.rs","stream_select.rs"]],\
"futures_sink":["",[],["lib.rs"]],\
"futures_task":["",[],["future_obj.rs","lib.rs","noop_waker.rs","spawn.rs"]],\
"futures_util":["",[["async_await",[],["join_mod.rs","mod.rs","pending.rs","poll.rs","select_mod.rs","stream_select_mod.rs"]],["future",[["future",[],["flatten.rs","fuse.rs","map.rs","mod.rs"]],["try_future",[],["into_future.rs","mod.rs","try_flatten.rs","try_flatten_err.rs"]]],["either.rs","join.rs","lazy.rs","maybe_done.rs","mod.rs","option.rs","pending.rs","poll_fn.rs","poll_immediate.rs","ready.rs","select.rs","try_join.rs","try_maybe_done.rs","try_select.rs"]],["sink",[],["close.rs","drain.rs","err_into.rs","fanout.rs","feed.rs","flush.rs","map_err.rs","mod.rs","send.rs","send_all.rs","unfold.rs","with.rs","with_flat_map.rs"]],["stream",[["stream",[],["all.rs","any.rs","chain.rs","collect.rs","concat.rs","count.rs","cycle.rs","enumerate.rs","filter.rs","filter_map.rs","flatten.rs","fold.rs","for_each.rs","forward.rs","fuse.rs","into_future.rs","map.rs","mod.rs","next.rs","peek.rs","scan.rs","select_next_some.rs","skip.rs","skip_while.rs","take.rs","take_until.rs","take_while.rs","then.rs","unzip.rs","zip.rs"]],["try_stream",[],["and_then.rs","into_stream.rs","mod.rs","or_else.rs","try_collect.rs","try_concat.rs","try_filter.rs","try_filter_map.rs","try_flatten.rs","try_fold.rs","try_for_each.rs","try_next.rs","try_skip_while.rs","try_take_while.rs","try_unfold.rs"]]],["empty.rs","iter.rs","mod.rs","once.rs","pending.rs","poll_fn.rs","poll_immediate.rs","repeat.rs","repeat_with.rs","select.rs","select_with_strategy.rs","unfold.rs"]],["task",[],["mod.rs","spawn.rs"]]],["fns.rs","lib.rs","never.rs","unfold_state.rs"]],\
"gcd":["",[],["lib.rs"]],\
"hash32":["",[],["fnv.rs","lib.rs","murmur3.rs"]],\
"hashbrown":["",[["external_trait_impls",[],["mod.rs"]],["raw",[],["alloc.rs","bitmask.rs","mod.rs","sse2.rs"]]],["lib.rs","macros.rs","map.rs","scopeguard.rs","set.rs"]],\
"heapless":["",[["pool",[["singleton",[],["arc.rs"]]],["cas.rs","mod.rs","singleton.rs"]]],["binary_heap.rs","deque.rs","histbuf.rs","indexmap.rs","indexset.rs","lib.rs","linear_map.rs","mpmc.rs","sealed.rs","sorted_linked_list.rs","spsc.rs","string.rs","vec.rs"]],\
"heck":["",[],["kebab.rs","lib.rs","lower_camel.rs","shouty_kebab.rs","shouty_snake.rs","snake.rs","title.rs","train.rs","upper_camel.rs"]],\
"humantime":["",[],["date.rs","duration.rs","lib.rs","wrapper.rs"]],\
"indexmap":["",[["map",[["core",[],["raw.rs"]]],["core.rs"]]],["arbitrary.rs","equivalent.rs","lib.rs","macros.rs","map.rs","mutable_keys.rs","set.rs","util.rs"]],\
"io_lifetimes":["",[],["example_ffi.rs","lib.rs","portability.rs","raw.rs","traits.rs","views.rs"]],\
"is_terminal":["",[],["lib.rs"]],\
"libc":["",[["unix",[["linux_like",[["linux",[["arch",[["generic",[],["mod.rs"]]],["mod.rs"]],["gnu",[["b64",[["x86_64",[],["align.rs","mod.rs","not_x32.rs"]]],["mod.rs"]]],["align.rs","mod.rs"]]],["align.rs","mod.rs","non_exhaustive.rs"]]],["mod.rs"]]],["align.rs","mod.rs"]]],["fixed_width_ints.rs","lib.rs","macros.rs"]],\
"linux_raw_sys":["",[["x86_64",[],["errno.rs","general.rs","ioctl.rs"]]],["lib.rs"]],\
"lock_api":["",[],["lib.rs","mutex.rs","remutex.rs","rwlock.rs"]],\
"log":["",[],["lib.rs","macros.rs"]],\
"memchr":["",[["memchr",[["x86",[],["avx.rs","mod.rs","sse2.rs"]]],["fallback.rs","iter.rs","mod.rs","naive.rs"]],["memmem",[["prefilter",[["x86",[],["avx.rs","mod.rs","sse.rs"]]],["fallback.rs","genericsimd.rs","mod.rs"]],["x86",[],["avx.rs","mod.rs","sse.rs"]]],["byte_frequencies.rs","genericsimd.rs","mod.rs","rabinkarp.rs","rarebytes.rs","twoway.rs","util.rs","vector.rs"]]],["cow.rs","lib.rs"]],\
"memoffset":["",[],["lib.rs","offset_of.rs","raw_field.rs","span_of.rs"]],\
"nu_ansi_term":["",[],["ansi.rs","debug.rs","difference.rs","display.rs","gradient.rs","lib.rs","rgb.rs","style.rs","util.rs","windows.rs","write.rs"]],\
"num_cpus":["",[],["lib.rs","linux.rs"]],\
"once_cell":["",[],["imp_std.rs","lib.rs","race.rs"]],\
"os_pipe":["",[],["lib.rs","unix.rs"]],\
"os_str_bytes":["",[["common",[],["mod.rs","raw.rs"]]],["iter.rs","lib.rs","pattern.rs","raw_str.rs"]],\
"overload":["",[],["assignment.rs","binary.rs","lib.rs","unary.rs"]],\
"pin_project_lite":["",[],["lib.rs"]],\
"pin_utils":["",[],["lib.rs","projection.rs","stack_pin.rs"]],\
"proc_macro2":["",[],["detection.rs","extra.rs","fallback.rs","lib.rs","marker.rs","parse.rs","rcvec.rs","wrapper.rs"]],\
"proc_macro_error":["",[["imp",[],["delegate.rs"]]],["diagnostic.rs","dummy.rs","lib.rs","macros.rs","sealed.rs"]],\
"proc_macro_error_attr":["",[],["lib.rs","parse.rs","settings.rs"]],\
"quote":["",[],["ext.rs","format.rs","ident_fragment.rs","lib.rs","runtime.rs","spanned.rs","to_tokens.rs"]],\
"rayon":["",[["collections",[],["binary_heap.rs","btree_map.rs","btree_set.rs","hash_map.rs","hash_set.rs","linked_list.rs","mod.rs","vec_deque.rs"]],["compile_fail",[],["cannot_collect_filtermap_data.rs","cannot_zip_filtered_data.rs","cell_par_iter.rs","mod.rs","must_use.rs","no_send_par_iter.rs","rc_par_iter.rs"]],["iter",[["collect",[],["consumer.rs","mod.rs"]],["find_first_last",[],["mod.rs"]],["plumbing",[],["mod.rs"]]],["chain.rs","chunks.rs","cloned.rs","copied.rs","empty.rs","enumerate.rs","extend.rs","filter.rs","filter_map.rs","find.rs","flat_map.rs","flat_map_iter.rs","flatten.rs","flatten_iter.rs","fold.rs","fold_chunks.rs","fold_chunks_with.rs","for_each.rs","from_par_iter.rs","inspect.rs","interleave.rs","interleave_shortest.rs","intersperse.rs","len.rs","map.rs","map_with.rs","mod.rs","multizip.rs","noop.rs","once.rs","panic_fuse.rs","par_bridge.rs","positions.rs","product.rs","reduce.rs","repeat.rs","rev.rs","skip.rs","skip_any.rs","skip_any_while.rs","splitter.rs","step_by.rs","sum.rs","take.rs","take_any.rs","take_any_while.rs","try_fold.rs","try_reduce.rs","try_reduce_with.rs","unzip.rs","update.rs","while_some.rs","zip.rs","zip_eq.rs"]],["slice",[],["chunks.rs","mergesort.rs","mod.rs","quicksort.rs","rchunks.rs"]]],["array.rs","delegate.rs","lib.rs","math.rs","option.rs","par_either.rs","prelude.rs","private.rs","range.rs","range_inclusive.rs","result.rs","split_producer.rs","str.rs","string.rs","vec.rs"]],\
"rayon_core":["",[["broadcast",[],["mod.rs"]],["compile_fail",[],["mod.rs","quicksort_race1.rs","quicksort_race2.rs","quicksort_race3.rs","rc_return.rs","rc_upvar.rs","scope_join_bad.rs"]],["join",[],["mod.rs"]],["scope",[],["mod.rs"]],["sleep",[],["counters.rs","mod.rs"]],["spawn",[],["mod.rs"]],["thread_pool",[],["mod.rs"]]],["job.rs","latch.rs","lib.rs","log.rs","private.rs","registry.rs","unwind.rs"]],\
"regex":["",[["literal",[],["imp.rs","mod.rs"]]],["backtrack.rs","compile.rs","dfa.rs","error.rs","exec.rs","expand.rs","find_byte.rs","input.rs","lib.rs","pikevm.rs","pool.rs","prog.rs","re_builder.rs","re_bytes.rs","re_set.rs","re_trait.rs","re_unicode.rs","sparse.rs","utf8.rs"]],\
"regex_syntax":["",[["ast",[],["mod.rs","parse.rs","print.rs","visitor.rs"]],["hir",[["literal",[],["mod.rs"]]],["interval.rs","mod.rs","print.rs","translate.rs","visitor.rs"]],["unicode_tables",[],["mod.rs"]]],["either.rs","error.rs","lib.rs","parser.rs","unicode.rs","utf8.rs"]],\
"rtic":["",[["export",[],["executor.rs"]]],["export.rs","lib.rs"]],\
"rtic_common":["",[],["dropper.rs","lib.rs","wait_queue.rs","waker_registration.rs"]],\
"rtic_core":["",[],["lib.rs"]],\
"rtic_macros":["",[["codegen",[["bindings",[],["cortex.rs"]]],["assertions.rs","async_dispatchers.rs","bindings.rs","hardware_tasks.rs","idle.rs","init.rs","local_resources.rs","local_resources_struct.rs","main.rs","module.rs","post_init.rs","pre_init.rs","shared_resources.rs","shared_resources_struct.rs","software_tasks.rs","util.rs"]],["syntax",[["parse",[],["app.rs","hardware_task.rs","idle.rs","init.rs","resource.rs","software_task.rs","util.rs"]]],["accessors.rs","analyze.rs","ast.rs","check.rs","parse.rs"]]],["analyze.rs","check.rs","codegen.rs","lib.rs","syntax.rs"]],\
"rtic_monotonics":["",[],["lib.rs","systick.rs"]],\
"rtic_sync":["",[],["arbiter.rs","channel.rs","lib.rs"]],\
"rtic_time":["",[],["lib.rs","linked_list.rs","monotonic.rs"]],\
"rustix":["",[["backend",[["linux_raw",[["arch",[["inline",[],["mod.rs","x86_64.rs"]]],["mod.rs"]],["io",[],["epoll.rs","errno.rs","mod.rs","poll_fd.rs","syscalls.rs","types.rs"]],["process",[],["cpu_set.rs","mod.rs","syscalls.rs","types.rs","wait.rs"]],["termios",[],["mod.rs","syscalls.rs","types.rs"]],["time",[],["mod.rs","types.rs"]]],["c.rs","conv.rs","elf.rs","mod.rs","reg.rs","weak.rs"]]]],["ffi",[],["mod.rs"]],["io",[],["close.rs","context.rs","dup.rs","errno.rs","eventfd.rs","fcntl.rs","ioctl.rs","is_read_write.rs","mod.rs","pipe.rs","poll.rs","read_write.rs","stdio.rs"]],["path",[],["arg.rs","mod.rs"]],["process",[],["chdir.rs","exit.rs","id.rs","kill.rs","membarrier.rs","mod.rs","prctl.rs","priority.rs","rlimit.rs","sched.rs","sched_yield.rs","uname.rs","wait.rs"]],["termios",[],["cf.rs","constants.rs","mod.rs","tc.rs","tty.rs"]]],["const_assert.rs","cstr.rs","lib.rs","utils.rs"]],\
"scopeguard":["",[],["lib.rs"]],\
"spin":["",[["mutex",[],["spin.rs"]]],["barrier.rs","lazy.rs","lib.rs","mutex.rs","once.rs","relax.rs","rwlock.rs"]],\
"stable_deref_trait":["",[],["lib.rs"]],\
"strsim":["",[],["lib.rs"]],\
"syn":["",[["gen",[],["clone.rs","debug.rs","eq.rs","hash.rs"]]],["attr.rs","await.rs","bigint.rs","buffer.rs","custom_keyword.rs","custom_punctuation.rs","data.rs","derive.rs","discouraged.rs","drops.rs","error.rs","export.rs","expr.rs","ext.rs","file.rs","gen_helper.rs","generics.rs","group.rs","ident.rs","item.rs","lib.rs","lifetime.rs","lit.rs","lookahead.rs","mac.rs","macros.rs","op.rs","parse.rs","parse_macro_input.rs","parse_quote.rs","pat.rs","path.rs","print.rs","punctuated.rs","reserved.rs","sealed.rs","span.rs","spanned.rs","stmt.rs","thread.rs","token.rs","tt.rs","ty.rs","verbatim.rs","whitespace.rs"]],\
"termcolor":["",[],["lib.rs"]],\
"unicode_ident":["",[],["lib.rs","tables.rs"]],\
"vcell":["",[],["lib.rs"]],\
"void":["",[],["lib.rs"]],\
"volatile_register":["",[],["lib.rs"]],\
"xtask":["",[],["argument_parsing.rs","build.rs","cargo_commands.rs","command.rs","main.rs"]]\
}');
createSourceSidebar();
